
%% Generating Signal
[Mt,fm] =audioread('eric.wav');
sound(Mt,fm);
fprintf('Original Sound is playing.. \n')
pause(length(Mt)/fm);
t=linspace(0,length(Mt)/fm,length(Mt));
figure('Name','Audio Signal');
subplot(4,1,1);
plot(t,Mt);
title('Time Domain');
Sf=fftshift(fft(Mt));
Sfvec=linspace(-fm/2,fm/2,length(Sf));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide ');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% filter
filter=ones(length(Mt),1);
f1=round((-4*1000+fm/2).*(length(Mt)/fm));
f2=round((4*1000+fm/2).*(length(Mt)/fm));
filter([1:f1  f2:end])=0;
Mf_Filtered=Sf;
Mf_Filtered=Mf_Filtered.*filter;
Mf_FilteredMag=abs(Mf_Filtered);
Mf_FilteredPhase=angle(Mf_Filtered);
Mt_Filtered=real(ifft(ifftshift(Mf_Filtered)));
sound(Mt_Filtered,fm);
fprintf('Filtered Sound is playing.. \n')
pause(length(Mt_Filtered)/fm); 
figure('Name','Filtered Audio Signal');
subplot(4,1,1);
plot(t,Mt_Filtered);
title('Time Domain');
subplot(4,1,2);
plot(Sfvec,Mf_Filtered);
title('Frequency Doamin');
subplot(4,1,3);
plot(Sfvec,Mf_FilteredMag);
title('Magneduide');
subplot(4,1,4);
plot(Sfvec,Mf_FilteredPhase);
title('Phase');
%% resample
fc=100000;
fs=5*fc;
Mt_Fil_res=resample(Mt_Filtered,fs,fm) ;
t1=linspace(0,length(Mt_Fil_res)/fs,length(Mt_Fil_res));
figure('Name','Resampled Filtered Audio Signal');
subplot(4,1,1);
plot(t1, Mt_Fil_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mt_Fil_res));
resvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_fil_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_fil_resphase);
title('Phase');
%% carrier
carrier_signal = cos(2*pi*fc*t1);
Ct=transpose(carrier_signal);
figure('Name','Carrier Signal');
subplot(4,1,1);
plot(t1, Ct);
title('Time Domain');
Sf=fftshift(fft(Ct));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% Modulated Signal
St=Mt_Fil_res .* Ct;
figure('Name','Modulated Signal');
subplot(4,1,1);
plot(t1, St);
title('Time Domain');
Sf=fftshift(fft(St));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% envelope detection
envolpe=abs(hilbert(St));
figure('Name','Recieved Signal with envelope detection');
subplot(4,1,1);
plot(t1, envolpe);
title('Time Domain');
Sf=fftshift(fft(envolpe));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% resample in envolpe detection
Mr_env_res=resample(envolpe,fm,fs) ;
t2=linspace(0,length(Mr_env_res)/fm,length(Mr_env_res));
sound(Mr_env_res,fm);
fprintf('Recieved Signal with envelope detection is playing.. \n');
pause(length(Mr_env_res)/fm); 
figure('Name','Resampled Recieved Signal with envelope detection');
subplot(4,1,1);
plot(t2, Mr_env_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mr_env_res));
resvec=linspace(-fs/2,fs/2,length(Mr_env_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_env_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_env_resphase);
title('Phase');
%% coherent detection
Vt=St .* Ct;
figure('Name','Recieved Signal with coherent detection');
subplot(4,1,1);
plot(t1, Vt);
title('Time Domain');
Vf=fftshift(fft(Vt));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Vf);
title('Frequency Doamin');
Sfmag=abs(Vf);
Sfphase=angle(Vf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% resample in coherent detection
Mr_coh_res=resample(Vt,fm,fs) ;
t3=linspace(0,length(Mr_coh_res)/fm,length(Mr_coh_res));
sound(Mr_coh_res,fm);
fprintf('Recieved Signal with coherent detection is playing.. \n');
pause(length(Mr_coh_res)/fm); 
figure('Name','Resampled Recieved Signal with coherent detection');
subplot(4,1,1);
plot(t3, Mr_coh_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mr_coh_res));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_fil_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_fil_resphase);
title('Phase');
%% Adding Noise
%% SNR 0dB
Mr_SNR1=awgn(Mr_coh_res,0);
sound(Mr_SNR1,fm);
fprintf('Recieved Signal with coherent detection with SNR 0dB is playing.. \n');
pause(length(Mr_SNR1)/fm); 
figure('Name','Resampled Recieved Signal with SNR 0dB ');
subplot(4,1,1);
plot(t3, Mr_SNR1);
title('Time Domain');
Mf_SNR1=fftshift(fft(Mr_SNR1));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_SNR1);
title('Frequency Doamin');
Mf_SNR1_resmag=abs(Mf_SNR1);
Mf_SNR1_resphase=angle(Mf_SNR1);
subplot(4,1,3);
plot(resvec,Mf_SNR1_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_SNR1_resphase);
title('Phase');

%% SNR 10dB
Mr_SNR2=awgn(Mr_coh_res,10);
sound(Mr_SNR2,fm);
fprintf('Recieved Signal with coherent detection with SNR 10dB is playing.. \n');
pause(length(Mr_SNR2)/fm); 
figure('Name','Resampled Recieved Signal with SNR 10dB');
subplot(4,1,1);
plot(t3, Mr_SNR2);
title('Time Domain');
Mf_SNR2=fftshift(fft(Mr_SNR2));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_SNR2);
title('Frequency Doamin');
Mf_SNR2_resmag=abs(Mf_SNR2);
Mf_SNR2_resphase=angle(Mf_SNR2);
subplot(4,1,3);
plot(resvec,Mf_SNR2_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_SNR2_resphase);
title('Phase');

%% SNR 30dB
Mr_SNR3=awgn(Mr_coh_res,30);
fprintf('Recieved Signal with coherent detection with SNR 30dB is playing.. \n');
sound(Mr_SNR3,fm);
pause(length(Mr_SNR3)/fm); 
figure('Name','Resampled Recieved Signal with SNR 30dB');
subplot(4,1,1);
plot(t3, Mr_SNR3);
title('Time Domain');
Mf_SNR3=fftshift(fft(Mr_SNR3));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_SNR3);
title('Frequency Doamin');
Mf_SNR3_resmag=abs(Mf_SNR3);
Mf_SNR3_resphase=angle(Mf_SNR3);
subplot(4,1,3);
plot(resvec,Mf_SNR3_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_SNR3_resphase);
title('Phase');
%% coherent detection with Frequency error
%% Frequency error =100
Carrier_freq_error_1 = cos(2*pi*(fs+100*(10^3))*t1);
Ct_freq_error_1=transpose(Carrier_freq_error_1);
Vt=St .* Ct_freq_error_1;
figure('Name','Recieved Signal with Frequency error =100');
subplot(4,1,1);
plot(t1, Vt);
title('Time Domain');
Vf=fftshift(fft(Vt));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Vf);
title('Frequency Doamin');
Sfmag=abs(Vf);
Sfphase=angle(Vf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% resample in coherent detection with freq error
Mr_coh_res=resample(Vt,fm,fs) ;
t3=linspace(0,length(Mr_coh_res)/fm,length(Mr_coh_res));
sound(Mr_coh_res,fm);
fprintf('Recieved Signal with coherent detection with Frequency error =100 is playing.. \n');
pause(length(Mr_coh_res)/fm); 
figure('Name','Resampled Recieved Signal with Frequency error =100');
subplot(4,1,1);
plot(t3, Mr_coh_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mr_coh_res));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_fil_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_fil_resphase);
title('Phase');
%% Frequency error =100.1
Carrier_freq_error_2 = cos(2*pi*(fs+100*(10^3))*t1);
Ct_freq_error_2=transpose(Carrier_freq_error_2);
Vt=St .* Ct_freq_error_2;
figure('Name','Recieved Signal with Frequency error =100.1');
subplot(4,1,1);
plot(t1, Vt);
title('Time Domain');
Vf=fftshift(fft(Vt));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Vf);
title('Frequency Doamin');
Sfmag=abs(Vf);
Sfphase=angle(Vf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% resample in coherent detection with freq error
Mr_coh_res=resample(Vt,fm,fs) ;
t3=linspace(0,length(Mr_coh_res)/fm,length(Mr_coh_res));
sound(Mr_coh_res,fm);
fprintf('Recieved Signal with coherent detection with Frequency error =100.1 is playing.. \n');
pause(length(Mr_coh_res)/fm); 
figure('Name','Resampled Recieved Signal with Frequency error =100.1');
subplot(4,1,1);
plot(t3, Mr_coh_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mr_coh_res));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_fil_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_fil_resphase);
title('Phase');
%% phase error
%% error = 20 degree
Carrier_phase_error = cos(2*pi*fc*t1+((20*pi)/180));
Ct_phase=transpose(Carrier_phase_error);
Vt=St .* Ct_phase;
figure('Name','Recieved Signal with phase error = 20 degree');
subplot(4,1,1);
plot(t1, Vt);
title('Time Domain');
Vf=fftshift(fft(Vt));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Vf);
title('Frequency Doamin');
Sfmag=abs(Vf);
Sfphase=angle(Vf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% resample in coherent detection with phase error
Mr_coh_res=resample(Vt,fm,fs) ;
t3=linspace(0,length(Mr_coh_res)/fm,length(Mr_coh_res));
sound(Mr_coh_res,fm);
fprintf('Recieved Signal with coherent detection with phase error = 20 degree is playing.. \n');
pause(length(Mr_coh_res)/fm); 
figure('Name','Resampled Recieved Signal with phase error = 20 degree');
subplot(4,1,1);
plot(t3, Mr_coh_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mr_coh_res));
resvec=linspace(-fs/2,fs/2,length(Mr_coh_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_fil_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_fil_resphase);
title('Phase');