
%% Generating Signal
[Mt,fm] =audioread('eric.wav');
sound(Mt,fm);
fprintf('Original Sound is playing.. \n');
pause(length(Mt)/fm);
t=linspace(0,length(Mt)/fm,length(Mt));
figure('Name','Audio Signal');
subplot(4,1,1);
plot(t,Mt);
title('Time Domain');
Sf=fftshift(fft(Mt));
Sfvec=linspace(-fm/2,fm/2,length(Sf));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide ');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');

%% filter
filter=ones(length(Mt),1);
f1=round((-4*1000+fm/2).*(length(Mt)/fm));
f2=round((4*1000+fm/2).*(length(Mt)/fm));
filter([1:f1  f2:end])=0;
Mf_Filtered=Sf;
Mf_Filtered=Mf_Filtered.*filter;
Mf_FilteredMag=abs(Mf_Filtered);
Mf_FilteredPhase=angle(Mf_Filtered);
Mt_Filtered=real(ifft(ifftshift(Mf_Filtered)));
sound(Mt_Filtered,fm);
fprintf('Filtered Sound is playing.. \n');
pause(length(Mt_Filtered)/fm); 
figure('Name','Filtered Audio Signal');
subplot(4,1,1);
plot(t,Mt_Filtered);
title('Time Domain');
subplot(4,1,2);
plot(Sfvec,Mf_Filtered);
title('Frequency Doamin');
subplot(4,1,3);
plot(Sfvec,Mf_FilteredMag);
title('Magneduide');
subplot(4,1,4);
plot(Sfvec,Mf_FilteredPhase);
title('Phase');

%% resample
fc=100000;
fs=5*fc;
Mt_Fil_res=resample(Mt_Filtered,fs,fm) ;
t1=linspace(0,length(Mt_Fil_res)/fs,length(Mt_Fil_res));
figure('Name','Resampled Filtered Audio Signal');
subplot(4,1,1);
plot(t1, Mt_Fil_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mt_Fil_res));
resvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_env_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_env_resphase);
title('Phase');
%% carrier
carrier_signal = cos(2*pi*fc*t1);
Ct=transpose(carrier_signal);
figure('Name','Carrier Signal');
subplot(4,1,1);
plot(t1, Ct);
title('Time Domain');
Sf=fftshift(fft(Ct));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% Modulated Signal
m=0.5;
A=max(Mt_Fil_res)/m;
St=(A+Mt_Fil_res).* Ct;
figure('Name','Modulated Signal');
subplot(4,1,1);
plot(t1, St);
title('Time Domain');
Sf=fftshift(fft(St));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% envolpe detection
envolpe=abs(hilbert(St))- 2* max(Mt_Fil_res);
figure('Name','Recieved Signal with envelope detection');
subplot(4,1,1);
plot(t1, envolpe);
title('Time Domain');
Sf=fftshift(fft(envolpe));
Sfvec=linspace(-fs/2,fs/2,length(Mt_Fil_res));
subplot(4,1,2);
plot(Sfvec,Sf);
title('Frequency Doamin');
Sfmag=abs(Sf);
Sfphase=angle(Sf);
subplot(4,1,3);
plot(Sfvec,Sfmag);
title('Magntuide');
subplot(4,1,4);
plot(Sfvec,Sfphase);
title('Phase');
%% resample in envolpe detection
Mr_env_res=resample(envolpe,fm,fs) ;
t2=linspace(0,length(Mr_env_res)/fm,length(Mr_env_res));
sound(Mr_env_res,fm);
fprintf('Recieved Signal with envelope detection is playing.. \n');
pause(length(Mr_env_res)/fm); 
figure('Name','Resampled Recieved Signal with envelope detection');
subplot(4,1,1);
plot(t2, Mr_env_res);
title('Time Domain');
Mf_env_res=fftshift(fft(Mr_env_res));
resvec=linspace(-fs/2,fs/2,length(Mr_env_res));
subplot(4,1,2);
plot(resvec,Mf_env_res);
title('Frequency Doamin');
Mf_env_resmag=abs(Mf_env_res);
Mf_env_resphase=angle(Mf_env_res);
subplot(4,1,3);
plot(resvec,Mf_env_resmag);
title('Magneduide');
subplot(4,1,4);
plot(resvec,Mf_env_resphase);
title('Phase');