[signal,Fs] = audioread('E:\Downloads_2\eric.wav');
sound(signal,Fs);
pause(8)
signal = signal(:,1);
figure(1);
subplot(2,1,1);
plot(signal);
title('before filter in time domain');
faxis = linspace(-Fs/2,Fs/2,length(signal));
SIGNAL = fftshift(fft(signal));
subplot(2,1,2);
plot(faxis,abs(SIGNAL));
xlabel('Frequency');
ylabel('Magnitude');
title('before filter in frequeny domain');
%-----------------Filter--------------------
n=length(signal)/Fs;
RightSide = round((Fs/2-4000)*n);
SIGNAL([1:RightSide length(signal)-RightSide+1:length(signal)]) = 0;
figure(2);
subplot(2,1,2);
plot(faxis,abs(SIGNAL));
xlabel('Frequency');
ylabel('Magnitude');
title('After filter in frequeny domain');
signal = real(ifft(ifftshift(SIGNAL)));
subplot(2,1,1);
plot(signal);
title('After filter in time domain');
sound(signal,Fs);
pause(8);
%-------------------5-DSB-SC--------------------------
CarrierFreq = 100000;
NewFs = 5 * CarrierFreq;
ResampledSignal = resample(signal,NewFs,Fs);
Time = linspace(0, length(ResampledSignal)/NewFs, length(ResampledSignal));
ScCarrier = cos(2*pi*CarrierFreq*Time)';
DSB_SC = ResampledSignal .* ScCarrier;
fftDSB_SC = fftshift(fft(DSB_SC));
faxis = linspace(-NewFs/2,NewFs/2,length(fftDSB_SC));
figure(3);
plot(faxis,abs(fftDSB_SC));
title('DSB-SC Signal');
%-------------------SSB-SC-------------------------
n=length(DSB_SC)/NewFs;
Filter = ones(length(DSB_SC),1);
RightSide = round(n*(CarrierFreq+(NewFs/2)));
LeftSide = round(n*(-CarrierFreq+(NewFs/2)));
Filter([1:LeftSide RightSide:end]) = 0;
LSB_SC = Filter .*fftDSB_SC;
figure(4);
plot(faxis,abs(LSB_SC));
title('SSB-SC Signal');
%--------------------CohenrentDetection SSB-SC----------------
LSB_SC_T= real(ifft(ifftshift(LSB_SC)));
RecievedLSB = LSB_SC_T.*ScCarrier;
fftRecievedLSB = fftshift(fft(RecievedLSB));
n=length(fftRecievedLSB)/NewFs;
LPF = ones(length(fftRecievedLSB),1);
RightSide = round(n*(4000+(NewFs/2)));
LeftSide = round(n*(-4000+(NewFs/2)));
LPF([1:LeftSide RightSide:end]) = 0;
OutputSignal=fftRecievedLSB .*LPF;
OutputSignalT=real(ifft(ifftshift(OutputSignal)));
ResampledOutputT=resample(OutputSignalT,Fs,NewFs);
ResampledOutputF=fftshift(fft(ResampledOutputT));
Faxis=linspace(-Fs/2,Fs/2,length(ResampledOutputF));
Taxis=linspace(0,length(ResampledOutputT)/Fs,length(ResampledOutputT));
figure(5);
subplot(2,1,1);
plot(Taxis,ResampledOutputT);
title('SSB-SC Recieved signal in Time domain');
subplot(2,1,2);
plot(Faxis,abs(ResampledOutputF));
title('SSB-SC Recieved signal in Frequency domain');
sound(ResampledOutputT,Fs)
pause(10);
%--------------------4th order Butterworth filter---------------\
[b,a]=butter(4,[CarrierFreq-4000 CarrierFreq]/(NewFs/2),'Bandpass');
LSB_ButterT=filter(b,a,DSB_SC);
LSB_ButterF=fftshift(fft(LSB_ButterT));
figure(6);
plot(faxis,abs(LSB_ButterF));
title('SSB-SC (Butterworth)');
%--------------------CohenrentDetection SSB-SC----------------
RecievedLSB = LSB_ButterT.*ScCarrier;
ResampledRecievedLSB=resample(RecievedLSB,Fs,NewFs);
[b,a]=butter(4,(4000 ./(2.*Fs)),'low');
OutputT=filter(b,a,ResampledRecievedLSB);
OutputF=fftshift(fft(ResampledRecievedLSB));
Faxis=linspace(-Fs/2,Fs/2,length(OutputF));
Taxis=linspace(0,length(OutputT)/Fs,length(OutputT));
figure(7);
subplot(2,1,2);
plot(Faxis,abs(OutputF));
title('SSB recieved signal in Frequency Domain(ButterWorth)');
subplot(2,1,1);
plot(Taxis,OutputT);
title('SSB recieved signal in Time Domain(ButterWorth)');
sound(OutputT,Fs) ;
pause(10);
%-----------------ssd_snr=0------------
lsb_Noise=awgn(LSB_SC_T,0);
recievedLsb_NoiseT=lsb_Noise.*ScCarrier;
recievedLsb_NoiseF=fftshift(fft(recievedLsb_NoiseT));
n=length(recievedLsb_NoiseF)/NewFs;
LPF = ones(length(recievedLsb_NoiseF),1);
RightSide = round(n*(4000+(NewFs/2)));
LeftSide = round(n*(-4000+(NewFs/2)));
LPF([1:LeftSide RightSide:end]) = 0;
OutputSignal_noise=recievedLsb_NoiseF .*LPF;
OutputSignal_noiseT=real(ifft(ifftshift(OutputSignal_noise)));
ResampledOutputT=resample(OutputSignal_noiseT,Fs,NewFs);
ResampledOutputF=fftshift(fft(ResampledOutputT));
Faxis=linspace(-Fs/2,Fs/2,length(ResampledOutputF));
Taxis=linspace(0,length(ResampledOutputT)/Fs,length(ResampledOutputT));
figure(8);
subplot(2,1,1);
plot(Taxis,ResampledOutputT);
title('SSB-SC Recieved signal with SNR=0 in Time domain');
subplot(2,1,2);
plot(Faxis,abs(ResampledOutputF));
title('SSB-SC Recieved signal with SNR=0 in Freq domain');
sound(ResampledOutputT,Fs)
pause(10);
% -----------------ssd_snr=10-------------------------
lsb_Noise=awgn(LSB_SC_T,10);
recievedLsb_NoiseT=lsb_Noise.*ScCarrier;
recievedLsb_NoiseF=fftshift(fft(recievedLsb_NoiseT));
n=length(recievedLsb_NoiseF)/NewFs;
LPF = ones(length(recievedLsb_NoiseF),1);
RightSide = round(n*(4000+(NewFs/2)));
LeftSide = round(n*(-4000+(NewFs/2)));
LPF([1:LeftSide RightSide:end]) = 0;
OutputSignal_noise=recievedLsb_NoiseF .*LPF;
OutputSignal_noiseT=real(ifft(ifftshift(OutputSignal_noise)));
ResampledOutputT=resample(OutputSignal_noiseT,Fs,NewFs);
ResampledOutputF=fftshift(fft(ResampledOutputT));
Faxis=linspace(-Fs/2,Fs/2,length(ResampledOutputF));
Taxis=linspace(0,length(ResampledOutputT)/Fs,length(ResampledOutputT));
figure(9);
subplot(2,1,1);
plot(Taxis,ResampledOutputT);
title('SSB-SC Recieved signal with SNR=10 in Time domain');
subplot(2,1,2);
plot(Faxis,abs(ResampledOutputF));
title('SSB-SC Recieved signal with SNR=10 in Freq domain');
sound(ResampledOutputT,Fs)
pause(10);
%-----------------ssd_snr=30-------------------------
lsb_Noise=awgn(LSB_SC_T,30);
recievedLsb_NoiseT=lsb_Noise.*ScCarrier;
recievedLsb_NoiseF=fftshift(fft(recievedLsb_NoiseT));
n=length(recievedLsb_NoiseF)/NewFs;
LPF = ones(length(recievedLsb_NoiseF),1);
RightSide = round(n*(4000+(NewFs/2)));
LeftSide = round(n*(-4000+(NewFs/2)));
LPF([1:LeftSide RightSide:end]) = 0;
OutputSignal_noise=recievedLsb_NoiseF .*LPF;
OutputSignal_noiseT=real(ifft(ifftshift(OutputSignal_noise)));
ResampledOutputT=resample(OutputSignal_noiseT,Fs,NewFs);
ResampledOutputF=fftshift(fft(ResampledOutputT));
Faxis=linspace(-Fs/2,Fs/2,length(ResampledOutputF));
Taxis=linspace(0,length(ResampledOutputT)/Fs,length(ResampledOutputT));
figure(10);
subplot(2,1,1);
plot(Taxis,ResampledOutputT);
title('SSB-SC Recieved signal with SNR=30 in Time domain');
subplot(2,1,2);
plot(Faxis,abs(ResampledOutputF));
title('SSB-SC Recieved signal with SNR=30 in Freq domain');
sound(ResampledOutputT,Fs)
pause(10);
%------------------------ SSB-TC----------------------------
Amplitude = max(ResampledSignal)./0.5;
transmitted_ssb=((Amplitude.*ScCarrier)+DSB_SC);
ffttransmitted_ssb=fftshift(fft(transmitted_ssb));
envelope=abs(hilbert(transmitted_ssb));
new=resample(envelope,Fs,NewFs);
Taxis=linspace(0,length(new)/Fs,length(new));
figure(11);
plot(Taxis,new);
title('SSB-TC Enelope Detector signal ');
sound(new,Fs);
